export const AUTHENTICATE_USER_START = "AUTHENTICATE_USER_START"
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS"
export const AUTHENTICATE_USER_FAILURE = "AUTHENTICATE_USER_FAILURE"

export const LOGOUT_USER = "LOGOUT_USER"

export const FETCH_TRUCKS_START = "FETCH_TRUCKS_START"
export const FETCH_TRUCKS_SUCCESS = "FETCH_TRUCKS_SUCCESS"
export const FETCH_TRUCKS_FAILURE = "FETCH_TRUCKS_FAILURE"